# not sure how to fix the cut-and-paste between Windows and Linux here.
# Effectively we have two separate config files.

# Linux config

package: anaconda_project

platform: linux-64

engine:
  - python=3.5
  - python=2.7

install:
  - conda install -y -q pip
  - pip install coverage flake8 pep257 pytest pytest-cov yapf==0.6.2 beautifulsoup4 tornado pytest-xdist
  - conda install -y -q redis pycrypto bcrypt ipython-notebook bokeh libffi ruamel_yaml anaconda-client requests

test:
  - LANG=en_US.UTF-8 python setup.py test

script:
  - conda build conda.recipe

build_targets: [conda]

--- # Windows config starts here

package: anaconda_project

platform:
  - win-32
  - win-64

engine:
  - python=2.7
  - python=3.5

install:
  # win32 build system doesn't seem to have psutil
  - conda install -y -q pip psutil
  - pip install pep257 yapf==0.6.2 pytest-xdist flake8
  - conda install -y -q pycrypto bcrypt ipython-notebook bokeh ruamel_yaml coverage beautifulsoup4 tornado pytest pytest-cov anaconda-client requests

test:
  - python setup.py test

before_script:
  - conda info
  - python -V

script:
  - conda install -n root -y psutil
  - conda build conda.recipe

---
platform: linux-64
engine: python=2.7
build_targets: /opt/miniconda/conda-bld/noarch/*.tar.bz2

iotimeout: 600
