package: anaconda_project

platform:
  - linux-64

engine:
  - python=2.7

test:
  - python setup.py develop > develop.output
  - python binstar/tests/runtests.py -v2  --skip-s3

script:
  - conda build conda.recipe

build_targets: [conda]
