package: anaconda_project

platform:
  - linux-64
  - win-64

engine:
  - python=3.5

install:
  - conda install -y -q pip
  - pip install coverage flake8 pep257 pytest pytest-cov yapf beautifulsoup4 ruamel.yaml tornado
  - conda install -y -q pycrypto
  - conda install -y -q bcrypt
  - conda install -y redis
  - conda install -y ipython-notebook
  - conda install -y bokeh

test:
  - LANG=en_US.UTF-8 python setup.py test

script:
  - conda build conda.recipe

build_targets: [conda]
