# Use `conda env create environment.yml` to create a dev environment
name: anaconda-project-dev
channels:
  # conda-forge is needed for pep257, but we prefer to pull
  # from Anaconda defaults whenever possible.
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - redis
  - notebook
  - ruamel_yaml
  - anaconda-client
  - requests
  - psutil
  - tornado>=4.2
  - pip
  - keyring
  - pytest
  - pytest-cov
  - coverage
  # Pinned just to help ensure that devs see consistent behavior
  # when reformatting the source. We have observed that the python
  # version can affect python behavior as well.
  - yapf==0.25.0
  - flake8
  - pep257
  # Optional; for multiprocessing tests
  - pytest-xdist
