commands: {default: {bokeh_app: main.py}}
variables: {}
downloads: {QUANTQUOTE: 'http://quantquote.com/files/quantquote_daily_sp500_83986.zip'}
dependencies: [bokeh=0.11.1, pandas, redis]
channels: []
environments: {}
