package:
  name: anaconda_project
  version: 0.1

build:
  script:
    - cd $RECIPE_DIR/..
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  test:
    - python
    - setuptools
    - coverage
    - flake8
    - pytest
    - pytest-cov
    - bcrypt
    - pyapf

  build:
    - python
    - setuptools
    - coverage
    - flake8
    - pytest
    - pytest-cov
    - bcrypt

  run:
    - beautifulsoup4
    - ruamel.yaml
    - tornado
    - pycrypto
    - bcrypt
