package:
  name: anaconda-project
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../
  # If you're trying to test build changes, you have to add this
  # pointing to the branch you're modifying.
  # git_tag: package-script

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - anaconda-project = anaconda_project.commands.main:main

requirements:
  build:
    - python
    - setuptools
    - psutil # needed by conda
    - tornado
    - "backports_abc >=0.4" # [py2k]
    - singledispatch
    - ruamel_yaml
    - beautifulsoup4
    - requests
    - anaconda-client

  run:
    - python
    - tornado
    - ruamel_yaml
    - beautifulsoup4
    - requests
    - anaconda-client

test:
  imports:
    - anaconda_project
  commands:
    - echo "First of test commands"
    - anaconda-project --help
    - anaconda-project --version
    - echo "Last of test commands"

about:
  home: https://github.com/Anaconda-Platform/anaconda-project/
  license: BSD
