package:
  name: anaconda_project
  version: 0.1

requirements:
  build:
    - python
    - setuptools
    - bcrypt

  run:
    - beautifulsoup4
    - ruamel.yaml
    - tornado
    - pycrypto
    - bcrypt
