package:
  name: anaconda_project
  version: 0.1

build:
  entry_points:
    - anaconda-project = project.commands.main:main

requirements:
  build:
    - python
    - setuptools
    - bcrypt

  run:
    - beautifulsoup4
    - ruamel.yaml
    - tornado
    - pycrypto
    - bcrypt
