package:
  name: anaconda_project
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  noarch_python: True
  entry_points:
    - anaconda-project = anaconda_project.commands.main:main

requirements:
  build:
    - python
    - setuptools
    - psutil # needed by conda

  run:
    - bcrypt
    - tornado
    - pycrypto
    - ruamel_yaml
    - beautifulsoup4
    - requests
    - anaconda-client

test:
  imports:
    - anaconda_project
  commands:
    - anaconda-project --help

about:
  home: https://github.com/Anaconda-Platform/anaconda-project/
  license: BSD
