package:
  name: conda-kapsel
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_url: ../
  # If you're trying to test build changes, you have to add this
  # pointing to the branch you're modifying.
  # git_tag: package-script

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - conda-kapsel = conda_kapsel.commands.main:main

requirements:
  build:
    - python
    - setuptools
    - psutil # needed by conda
    - tornado
    - "backports_abc >=0.4" # required by tornado, not pulled in automatically?
    - ruamel_yaml
    - beautifulsoup4
    - requests
    - anaconda-client
    - "keyring >=9.0"

  run:
    - python
    - tornado
    - ruamel_yaml
    - beautifulsoup4
    - requests
    - anaconda-client
    - "keyring >=9.0"

test:
  imports:
    - conda_kapsel
  commands:
    - echo "First of test commands"
    - conda-kapsel --help
    - conda-kapsel --version
    - echo "Last of test commands"

about:
  home: https://github.com/Anaconda-Platform/conda-kapsel/
  license: BSD
